title: Everything About GitHub
author: Wasp.iSpy
email: nseabasionyinyechukwu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog that keeps you updated on  everything about [**GitHub**](www.github.com)
# social links
twitter_username: @wasp_ispy
github_username:  @jessica-Andrew

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
